environment_variables:
  secretRefName: auth-secrets-dev
  secrets:
    ENV_AUTH_DATASOURCE_USERNAME: replace
    ENV_AUTH_DATASOURCE_PASSWORD: replace

  secret_files:
    ENV_AUTH_KAFKA_KEYSTORE: ""

  configmap:
    values:
      ENV_AUTH_DATASOURCE_URL: "jdbc:postgresql://postgresql:5432/user_db"



autoscaling:
  minReplicas: 2
  maxReplicas: 2

env:
  SPRING_PROFILES_ACTIVE: "dev"

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: true
  className: "nginx"
  host: "auth-dev.example.com"
  tls:
    enabled: false

secrets:
  existingSecretName: ""

hpa:
  enabled: false

pdb:
  enabled: false

metrics:
  servicemonitor:
    enabled: false

