apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql.fullname" . }}-config
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
data:
  {{- if .Values.postgresql.config }}
  postgresql.conf: |
    {{- range $k, $v := .Values.postgresql.config }}
    {{ $k }} = {{ $v | quote }}
    {{- end }}
  {{- end }}

  {{- if and .Values.initdb.enabled .Values.initdb.scripts }}
  {{- range $name, $content := .Values.initdb.scripts }}
  {{ $name }}: |
  {{ $content | indent 4 }}
  {{- end }}
  {{- end }}
